services:

  OxidEsales\GraphQl\Service\DeveloperToolsServiceInterface:
    class: OxidEsales\GraphQl\Service\DeveloperToolsService
    public: true
    autowire: true

  OxidEsales\GraphQl\Service\DeveloperPermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    public: false
    autowire: true
    calls:
      - ['addPermission', ['developer', '*']]
    tags:
      - {name: 'graphql_permissions_provider'}
