services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Developer\Service\DeveloperToolsServiceInterface:
    class: OxidEsales\GraphQL\Developer\Service\DeveloperToolsService
    public: true

  OxidEsales\GraphQL\Developer\Service\DeveloperAuthenticationServiceInterface:
    class: OxidEsales\GraphQL\Developer\Service\DeveloperAuthenticationService

  OxidEsales\GraphQL\Developer\Service\DeveloperAuthorizationEventSubscriber:
    class: OxidEsales\GraphQL\Developer\Service\DeveloperAuthorizationEventSubscriber
    tags: ['kernel.event_subscriber']
